/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'unplugin-vue-router/types'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<'/', '/', Record<never, never>, Record<never, never>>,
    '/AboutView': RouteRecordInfo<'/AboutView', '/AboutView', Record<never, never>, Record<never, never>>,
    '/basket/': RouteRecordInfo<'/basket/', '/basket', Record<never, never>, Record<never, never>>,
    '/basket/edit/[data]': RouteRecordInfo<'/basket/edit/[data]', '/basket/edit/:data', { data: ParamValue<true> }, { data: ParamValue<false> }>,
    '/basket/exemple/[data]': RouteRecordInfo<'/basket/exemple/[data]', '/basket/exemple/:data', { data: ParamValue<true> }, { data: ParamValue<false> }>,
    '/basket/NewBasket': RouteRecordInfo<'/basket/NewBasket', '/basket/NewBasket', Record<never, never>, Record<never, never>>,
    '/IndexView': RouteRecordInfo<'/IndexView', '/IndexView', Record<never, never>, Record<never, never>>,
  }
}
